---

- name: Set up PostgreSQL Database
  hosts: db
  roles:
    - db/setup_postgres_apt
    - db/install_postgres
    - role: db/setup_pg_user
      vars:
        user: "{{ local_loop.db }}"
    - role: db/setup_pg_user
      vars:
        user: "{{ local_loop.minion_db }}"
    - role: db/setup_pg_database
      vars:
        db: "{{ local_loop.db }}"
    - role: db/setup_pg_database
      vars:
        db: "{{ local_loop.minion_db }}"