---

- name: Set up Web Servers
  hosts: web
  roles:
    - db/setup_postgres_apt
    - perl/install_dependencies
    - perl/install_plenv
    - web/server_repo
    - web/pg_service
    - web/config
    - web/storage
    - web/schema_setup