---

- name: Clone Local Loop Server Repo
  git:
    repo: https://github.com/Pear-Trading/Foodloop-Server.git
    dest: ~/Foodloop-Server
    clone: yes
  become: yes
  become_user: "{{ local_loop.runtime_user }}"

- name: Install Perl Modules
  shell: ~/.plenv/bin/plenv exec cpanm --installdeps . --with-feature=postgres --with-feature=codepoint-open
  args:
    chdir: ~/Foodloop-Server
  become: yes
  become_user: "{{ local_loop.runtime_user }}"