---

- name: Clone Local Loop Server Repo
  git:
    repo: https://github.com/Pear-Trading/Foodloop-Server.git
    dest: "{{ local_loop.paths.root }}"
    clone: yes
    version: "{{ local_loop.server_branch }}"
  become: yes
  become_user: "{{ local_loop.runtime.user }}"

- name: Install Perl Modules
  shell: ~/.plenv/bin/plenv exec cpanm --installdeps . --with-feature=postgres --with-feature=codepoint-open --quiet
  args:
    chdir: ~/Foodloop-Server
  register: cpanm_result
  changed_when: cpanm_result.stdout != ""
  become: yes
  become_user: "{{ local_loop.runtime.user }}"