---

- name: Add Official PostgreSQL Apt Key
  apt_key:
    id: B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  become: yes
  become_user: root

- name: Add Official Postgres Apt Repo
  apt_repository:
    repo: deb https://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main
    state: present
    filename: pgdg
  become: yes
  become_user: root