---

- name: Check if db deployed
  stat:
    path: "{{ local_loop.runtime.home }}/.localloop-schema-installed"
  register: db_install_check
  become: yes
  become_user: "{{ local_loop.runtime.user }}"

- name: Install DB Schema
  shell: "~/.plenv/bin/plenv exec perl script/deploy_db install -c 'dbi:Pg:service=local_loop'"
  args:
    chdir: "{{ local_loop.paths.root }}"
  when: db_install_check.stat.exists == False
  become: yes
  become_user: "{{ local_loop.runtime.user }}"

# Runs after the install, so should only happen when the command succeeds
- name: Set DB Deployed Checkfile
  file:
    path: "{{ local_loop.runtime.home }}/.localloop-schema-installed"
    state: touch
    mode: 0444
  when: db_install_check.stat.exists == False
  become: yes
  become_user: "{{ local_loop.runtime.user }}"

- name: Upgrade DB Schema
  shell: "~/.plenv/bin/plenv exec perl script/deploy_db upgrade -c 'dbi:Pg:service=local_loop'"
  args:
    chdir: "{{ local_loop.paths.root }}"
  register: db_upgrade
  when: db_install_check.stat.exists == True
  changed_when: '"no need to run upgrade" not in db_upgrade.stderr'
  become: yes
  become_user: "{{ local_loop.runtime.user }}"
