---

- name: Setup Pg Service Config
  template:
    src: pg_service.conf.j2
    dest: ~/.pg_service.conf
    mode: '0600'
    owner: "{{ local_loop.runtime_user }}"
    group: "{{ local_loop.runtime_group }}"
  become: yes