---

- name: Setup Pg Service Config
  template:
    src: pg_service.conf.j2
    dest: "{{ local_loop.runtime.home }}/.pg_service.conf"
    mode: '0600'
    owner: "{{ local_loop.runtime.user }}"
    group: "{{ local_loop.runtime.group }}"
  become: yes